version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tickether

  db:
    image: db
    ports:
      - "3004:3004"
    links:
      - postgres
    environment:
      DATABASEUSER: docker
      DATABASEPASSWORD: docker
      DATABASEPORT: postgres:5432
    depends_on:
      - postgres

  eth:
    image: eth
    ports:
      - "3002:3002"
    links:
      - db
    depends_on:
      - db


  auth:
    image: auth
    ports:
      - "3003:3003"
    links:
      - db
    depends_on:
      - db
    environment:
      DB_SERVER_URL: http://db
